### ISSUE TITLE
Missing load_normalize_clean.csv file to genenera the data

### ISSUE THREAD

**Issue by hunglkuit** [xuwkk/Visual-Power-Grid#1]
Dear @xuwkk,
Thank you so much for sharing your works. Currently, the file "load_normalize_clean.csv" in the src directory is missing, so we can not generate the data to run your code. It would be great if you can share such file.

Best regards,
Kim Hung

**Comment by xuwkk** [comment]
Hey, thanks for your insterests. I have add the link to the source data in readme.

Best,
Wangkun
